### ISSUE TITLE
Songs show wrong duration in Queue

### ISSUE THREAD

**Issue by colby** [nijotz/shitstream#13]
Some songs show as only several seconds in the Queue page.

![screen shot 2014-08-27 at 11 48 17 am](https://cloud.githubusercontent.com/assets/111192/4065453/b98bb3ba-2e1a-11e4-8539-63b96cc80b1c.png)

**Comment by colby** [comment]
Bug

**Comment by nijotz** [comment]
From mpd logs:

```
ffmpeg/mp3: Estimating duration from bitrate, this may be inaccurate
```

I'll look into MPD bugs, workarounds.
